[package]
name = "openapi-axum-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
openapiv3 = "2.0.0"
axum = "0.8.1"
utoipa = "5.3.0"
askama = "0.12.1"

